### ISSUE TITLE
What color themes do you use?

### ISSUE THREAD

**Issue by cilice** [zkat/ama#6]
Like in your editor, terminal, or anywhere else.

**Comment by zkat** [comment]
I have tried, but my eyes simply can't handle light-background themes for code-related things, as such, my `hyperterm` theme is just the default dark color scheme. In my editor(s) I use the fabulous [fairy-floss theme](http://sailorhg.github.io/fairyfloss/) by @sailorhg. When I was still using emacs, I was using @robotlolita's [candy-chain theme](https://github.com/robotlolita/candy-chain), which is still one of the nicest I've ever used. When I was coding Lisp, I would also configure `()` to be nearly the same color as the background, cause I didn't usually look at them anyway.

idk what it is about light themes, but it's like my eyes just can't contrast all the colors as well, so the syntax highlighting doesn't jump out at me enough.
