### ISSUE TITLE
Effective Traits.

### ISSUE THREAD

**Issue by cjoulain** [zkat/ama#8]
What qualities do you feel are especially necessary for those who are just starting out in web development (or careers in tech in general)?

And what qualities are especially useful for those who are involved in community management?

**Comment by zkat** [comment]
### Qualities for Web Dev/Tech Careers

🤔... I guess the only thing I can even think of that's consistently useful is **a vague interest in learning and improving** (whether on-the-job, as a hobby, or as a formal study or self-study process), but not even in the sense of obsessing over learning all the little details. Just be okay with growing and have some skills that facilitate it.

The following are possible answers, and why **I don't think they're actually necessary**:
- "Be really good at a technology and master it" - You never really need to be completely masterful in any single skill. Focus on doing something, even a wide range of things, that you find interesting. Do your work and let your career grow over time. You can have a happy, successful, productive career without ever becoming one of those super masterful hackerdevs.
- "Be pretty alright at a wide range of things and learn them fast" - See above: Whether you focus or spread out, or whether you get Extremely Good, are not things that determine whether you have a happy, successful, productive career.
- "Be kind" - look this is just general life advice. I think everyone should learn to be kind. It is also a skill you learn. Please learn it. But if you're worried that your social awkwardness/difficulty/etc are gonna stop you from having a career, then tbh that's not true. I've worked with plenty of unapologetic assholes in my time, and they were getting paid plenty for cozy, cushy jobs :\
- "Have a natural sense of curiosity, doing things for the sake of them, and code for fun" - no this is bullshit stop perpetuating these myths about some magical ideal programmer. I definitely fall into this category myself. I even have used (and occasionally still use) the "hacker" label on myself. This does not make me that special, and is simply a way for me to communicate that I like doing this sort of thing for fun. It _has_ benefitted me, but actually going to school, or dedicated self-study by those who just wanted a good, productive career, have not been much different (possibly even been better) than the approach I took.
- "Get a degree in CS/Go to a bootcamp" - You can get some good grounding at these places. You can also read a book. Do what works for you. Nothing fundamental here.

### Getting Involved in Community Management

This one does have some qualities that I think are important:
- Get to know a wide variety of people and learn about them and their views of the world.
- Practice empathy actively. That means actually stop yourself from assuming and actually examine, talk about, and ask about, what someone's worldview is. Specially when situations are hard.
- Grow your professional network.
- Learn to yield the floor. Community management is about community. Not just you. Let things be what they will.

**Comment by abdulhannanali** [comment]
@zkat You should definitely convert it to a blog post. That's some really good advice here. Thank you for this and your work in Open source community <3
